download and delete files
Frozen-Dark/CloudDriveTs pull request #5
Opened 2024-01-10 20:16 UTC by Frozen-Dark

2024-01-12 22:35 UTC, pashokitsme requested changes
Ты зачем то используешь мидллвейры вообще для всего. 
Эндпоинты - это эндпоинты, они содержат логику, а не обрабатывают исключения. Исключение должна обрабатывать миддлтварь на выходе и выдавать адекватную ошибку.
Также, думаю, что api не должен возвращать человекочитаемые ошибки. Только код и описание, а `Файл не удалось скачать по такой то крутой причине` уже рисует вебморда

2024-01-12 22:35 UTC, pashokitsme commented on client/src/actions/file.ts
> +	}
Исключение глотается

2024-01-12 22:35 UTC, pashokitsme commented on client/src/actions/file.ts
> +	}
Исключение глотается

2024-01-12 22:35 UTC, pashokitsme commented on client/src/actions/file.ts
> +	}
Тут тоже

2024-01-12 22:35 UTC, pashokitsme commented on client/src/actions/folder.ts
> +	}
зачем `{ }`?

2024-01-12 22:35 UTC, pashokitsme commented on client/src/app/providers/FileProvider/lib/FileContext.ts
>  }
Почему `FileContextType` это интерфейс из полей и методов, а не перечисление типов?
Почему `void`, а не `Promise<void>`?

2024-01-12 22:35 UTC, pashokitsme commented on client/src/components/DiskComponents/DiskPopup/DiskPopup.tsx
> +	}
`{ }` не нужны

2024-01-12 22:35 UTC, pashokitsme commented on client/src/components/DiskComponents/DiskPopup/DiskPopup.tsx
> +	const name = activeItem.type === "file" ? (activeItem as any).item.fileName : (activeItem as any).item.folderName;
`any`

2024-01-12 22:35 UTC, pashokitsme commented on client/src/components/DiskComponents/DiskPopup/DiskPopup.tsx
> +	};
Избавься от вложенных `if`, или удали ненужные `{ }`, неудобно читать

2024-01-12 22:35 UTC, pashokitsme commented on client/src/components/DiskComponents/Folder.tsx
> +	folderClick: (folder: FolderAttributes) => void;
нет префикса `on`

2024-01-12 22:35 UTC, pashokitsme commented on client/src/components/DiskComponents/Folder.tsx
>  	};
Тогда уж сделай инлайновыми, всё равно одна строка

2024-01-12 22:35 UTC, pashokitsme commented on client/src/pages/Disk/Disk.tsx
> +	type: "folder" | "file";
Думаю имеет смысл вынести `folder | file` в отдельный тип

2024-01-12 22:35 UTC, pashokitsme commented on client/src/pages/Disk/Disk.tsx
> +		const type = (item as any)?.fileName ? "file" : "folder";
`as any`

2024-01-12 22:35 UTC, pashokitsme commented on server/controllers/fileController.ts
>  }
Похоже, что ты предполагаешь, что `download` - это эндпоинт, а не миддлтварь. А используешь как её.

2024-01-12 22:35 UTC, pashokitsme commented on server/routes/folderRouter.ts
> +router.put("/move", folderController.move);
Не делается так. У тебя один роут с разными методами, `POST /` - создаёт, `DELETE /` - удаляет ресурс, `PUT /` - переименовывает и так далее

2024-01-12 22:35 UTC, pashokitsme commented on server/routes/index.ts
> +indexRouter.use("/folder", folderRouter);
Это должны быть эндпоинты, а не миддлвейры

2024-01-12 22:35 UTC, pashokitsme commented on server/services/fileService.ts
> +		const { mino, userId, fileId } = props;
`minio`

2024-01-12 22:35 UTC, pashokitsme commented on server/services/minoService.ts
> +		return mino.getObject(bucketName, filePath);
`minio`

2024-01-14 15:47 UTC, Frozen-Dark commented on client/src/app/providers/FileProvider/lib/FileContext.ts
>  }
Потому что он не асинхронный XD

2024-01-14 16:32 UTC, Frozen-Dark commented on client/src/components/DiskComponents/DiskPopup/DiskPopup.tsx
> +	};
Я подумаю на счет вынесения такой логики из компонентов, потому что она 100% нужна в дальнейшем, пока надо быстро закончить курсач и сдать его

2024-01-14 16:32 UTC, Frozen-Dark commented on client/src/pages/Disk/Disk.tsx
> +	type: "folder" | "file";
Пока используется в 1 месте, потом эти типы уедут в хук и их не будет в компоненте Disk

2024-01-14 16:32 UTC, Frozen-Dark commented on server/controllers/fileController.ts
>  }
Загрузка пайпом это база, тут стрим кидаем на клиент и все счастливы, а по другому я не знаю как сделать

2024-01-14 16:32 UTC, Frozen-Dark commented on server/routes/folderRouter.ts
> +router.put("/move", folderController.move);
Когда в квери передаешь данные, они всегда стринг, потом возникают проблемы с типизацией, поэтому пока не использую семантику для части запросов.

2024-01-14 16:32 UTC, Frozen-Dark commented on server/routes/index.ts
> +indexRouter.use("/folder", folderRouter);
с index роутером удобнее, и надо бы mino вынести, на уровень ниже

2024-01-14 16:32 UTC, Frozen-Dark commented on server/services/fileService.ts
> +		const { mino, userId, fileId } = props;
![image](https://github.com/Frozen-Dark/CloudDriveTs/assets/116309190/c1441770-900e-4ad7-b513-e8dd2a96c3cb) 
Тут тоже mino, мне удобнее не minio а mino, я понимаю что неправильно. Байты экономлю на сервере.
![image](https://github.com/Frozen-Dark/CloudDriveTs/assets/116309190/86607ab3-16e1-4b60-951d-112ce597de13)

2024-01-14 16:58 UTC, merged

2024-01-14 17:33 UTC, pashokitsme commented on server/routes/index.ts
> +indexRouter.use("/folder", folderRouter);
Вопрос не в `indexRouter`, а в `use`